"""add_hums_telemetry_fields_and_indexes

Revision ID: 0286e4b9a882
Revises: 9fe9c2b0cc7d
Create Date: 2026-09-13 20:44:59.394171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0286e4b9a882'
down_revision: Union[str, None] = '9fe9c2b0cc7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.add_column('sensor_readings', sa.Column('component_id', sa.String(length=50), nullable=True))
    op.add_column('sensor_readings', sa.Column('component_type', sa.String(length=50), nullable=True))
    op.add_column('sensor_readings', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('fuel_pressure', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('battery_voltage', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('coolant_temperature', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('load_percentage', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('ambient_temperature', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_status', sa.String(length=20), nullable=True))
    op.add_column('sensor_readings', sa.Column('anomaly_label', sa.Integer(), nullable=True))
    op.add_column('sensor_readings', sa.Column('failure_within_50_hours', sa.Integer(), nullable=True))
    op.alter_column('sensor_readings', 'vibration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'oil_pressure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'rpm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'hydraulic_pressure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'operating_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'engine_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'fuel_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index('ix_sensor_readings_asset_timestamp', 'sensor_readings', ['asset_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_component_id'), 'sensor_readings', ['component_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_component_type'), 'sensor_readings', ['component_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_component_type'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_component_id'), table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_asset_timestamp', table_name='sensor_readings')
    op.alter_column('sensor_readings', 'fuel_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensor_readings', 'engine_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensor_readings', 'operating_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensor_readings', 'hydraulic_pressure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensor_readings', 'rpm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensor_readings', 'oil_pressure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensor_readings', 'vibration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('sensor_readings', 'failure_within_50_hours')
    op.drop_column('sensor_readings', 'anomaly_label')
    op.drop_column('sensor_readings', 'sensor_status')
    op.drop_column('sensor_readings', 'ambient_temperature')
    op.drop_column('sensor_readings', 'load_percentage')
    op.drop_column('sensor_readings', 'coolant_temperature')
    op.drop_column('sensor_readings', 'battery_voltage')
    op.drop_column('sensor_readings', 'fuel_pressure')
    op.drop_column('sensor_readings', 'temperature')
    op.drop_column('sensor_readings', 'component_type')
    op.drop_column('sensor_readings', 'component_id')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    # ### end Alembic commands ###
