"""add_enhanced_maintenance_fields

Revision ID: 3f89cd33e4fa
Revises: c81104cede48
Create Date: 2026-09-13 21:34:34.402469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f89cd33e4fa'
down_revision: Union[str, None] = 'c81104cede48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_records', sa.Column('component_id', sa.String(length=50), nullable=True))
    op.add_column('maintenance_records', sa.Column('component_type', sa.String(length=100), nullable=True))
    op.add_column('maintenance_records', sa.Column('operating_hours', sa.Float(), nullable=True))
    op.add_column('maintenance_records', sa.Column('issue_detected', sa.String(length=255), nullable=True))
    op.add_column('maintenance_records', sa.Column('failure_type', sa.String(length=100), nullable=True))
    op.add_column('maintenance_records', sa.Column('component_condition', sa.String(length=50), nullable=True))
    op.add_column('maintenance_records', sa.Column('parts_replaced', sa.String(length=100), nullable=True))
    op.add_column('maintenance_records', sa.Column('failure_occurred', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('maintenance_records', sa.Column('maintenance_duration_hours', sa.Float(), nullable=True))
    op.add_column('maintenance_records', sa.Column('next_maintenance_due_hours', sa.Float(), nullable=True))
    op.add_column('maintenance_records', sa.Column('maintenance_status', sa.String(length=50), nullable=False, server_default=sa.text("'COMPLETED'")))

    op.create_index(op.f('ix_maintenance_records_component_id'), 'maintenance_records', ['component_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_component_type'), 'maintenance_records', ['component_type'], unique=False)
    op.create_index(op.f('ix_maintenance_records_failure_type'), 'maintenance_records', ['failure_type'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_status'), 'maintenance_records', ['maintenance_status'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_type'), 'maintenance_records', ['maintenance_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_maintenance_type'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_maintenance_status'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_failure_type'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_component_type'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_component_id'), table_name='maintenance_records')
    op.drop_column('maintenance_records', 'maintenance_status')
    op.drop_column('maintenance_records', 'next_maintenance_due_hours')
    op.drop_column('maintenance_records', 'maintenance_duration_hours')
    op.drop_column('maintenance_records', 'failure_occurred')
    op.drop_column('maintenance_records', 'parts_replaced')
    op.drop_column('maintenance_records', 'component_condition')
    op.drop_column('maintenance_records', 'failure_type')
    op.drop_column('maintenance_records', 'issue_detected')
    op.drop_column('maintenance_records', 'operating_hours')
    op.drop_column('maintenance_records', 'component_type')
    op.drop_column('maintenance_records', 'component_id')
    # ### end Alembic commands ###
