"""add_readiness_assessments_table

Revision ID: c81104cede48
Revises: e8e00ba16dc4
Create Date: 2026-09-13 21:19:07.522371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81104cede48'
down_revision: Union[str, None] = 'e8e00ba16dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readiness_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('readiness_state', sa.String(length=50), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=True),
    sa.Column('rul_hours', sa.Float(), nullable=True),
    sa.Column('predicted_failure_mode', sa.String(length=100), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('primary_reason', sa.Text(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_assessments_asset_id'), 'readiness_assessments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_readiness_assessments_created_at'), 'readiness_assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_readiness_assessments_id'), 'readiness_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_readiness_assessments_readiness_state'), 'readiness_assessments', ['readiness_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readiness_assessments_readiness_state'), table_name='readiness_assessments')
    op.drop_index(op.f('ix_readiness_assessments_id'), table_name='readiness_assessments')
    op.drop_index(op.f('ix_readiness_assessments_created_at'), table_name='readiness_assessments')
    op.drop_index(op.f('ix_readiness_assessments_asset_id'), table_name='readiness_assessments')
    op.drop_table('readiness_assessments')
    # ### end Alembic commands ###
